### PR TITLE
feat(database): add timestamp attribute on rating table

### PR DESCRIPTION
**Pull request by imbensonchiu**
See #22

The timestamp is randomly selected between 2023/12/01 00:00:00 and 2023/12/31 23:59:59

### CODE REVIEW

**Review by yenting-biao — APPROVED** [review]
OK

**Review by yenting-biao — DISMISSED** [review]
Good

**Comment by togimoto** [comment]
f156574's commit message:
> fix(database): keep only one backup file, revise ref. triggers 

@imbensonchiu Can you elaborate on what changed you have made to the referential triggers, and any other changes?

**Comment by imbensonchiu** [comment]
> [f156574](https://github.com/112-1-Database-Management-Final-Project/ntu-book/commit/f15657467cb787df262ecbbba1551ec51def1ba0)'s commit message:
> 
> > fix(database): keep only one backup file, revise ref. triggers
> 
> @imbensonchiu Can you elaborate on what changed you have made to the referential triggers, and any other changes?

Sorry. 

Changes are what we have done on the meeting this Monday, but I guess we forgot to record what have been changed.

**Comment by imbensonchiu** [comment]
Update: textbook table has been added

**Review by togimoto — CHANGES_REQUESTED** [review]
todo: Change name of `timestamp` attribute in `rating` to `ratingtimestamp` as per the schema.

rating

**Comment by yenting-biao** [comment]
@togimoto 這樣我 ER 也要改？我禮拜一是根據新資料庫改的，我是寫 Timestamp

**Comment by togimoto** [comment]
> @togimoto 這樣我 ER 也要改？我禮拜一是根據新資料庫改的，我是寫 Timestamp

Yes please, thank you!

**Comment by yenting-biao** [comment]
> > @togimoto 這樣我 ER 也要改？我禮拜一是根據新資料庫改的，我是寫 Timestamp
> 
> Yes please, thank you!

Updated

**Comment by imbensonchiu** [comment]
> todo: Change name of `timestamp` attribute in `rating` to `ratingtimestamp` as per the schema.
> 
> rating

Changed

**Review by togimoto — APPROVED** [review]

**Pull request merged**
